const colors = {
  light: {
    text: "#1C1235",
    tint: "#6C3FEF",
    background: "#F7F5FF",
    foreground: "#1C1235",
    card: "#FFFFFF",
    cardForeground: "#1C1235",
    primary: "#6C3FEF",
    primaryForeground: "#FFFFFF",
    secondary: "#EEE9FF",
    secondaryForeground: "#6C3FEF",
    muted: "#F0ECFF",
    mutedForeground: "#7B6FA8",
    accent: "#10B981",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E3DCFF",
    input: "#E3DCFF",
  },
  dark: {
    text: "#F0ECFF",
    tint: "#9F7AEA",
    background: "#0F0B1E",
    foreground: "#F0ECFF",
    card: "#1A1533",
    cardForeground: "#F0ECFF",
    primary: "#9F7AEA",
    primaryForeground: "#FFFFFF",
    secondary: "#241D3B",
    secondaryForeground: "#C4B5FD",
    muted: "#1D1836",
    mutedForeground: "#8B7FBA",
    accent: "#34D399",
    accentForeground: "#000000",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#2D2553",
    input: "#2D2553",
  },
  radius: 16,
};

export default colors;
