import type { Category } from "@/context/ExpenseContext";

const KEYWORDS: Record<Exclude<Category, "other">, string[]> = {
  food: [
    "restaurant",
    "cafe",
    "pizza",
    "burger",
    "zomato",
    "swiggy",
    "food",
    "lunch",
    "dinner",
    "breakfast",
    "coffee",
    "bakery",
    "dominos",
    "kfc",
    "mcdonalds",
    "starbucks",
    "biryani",
    "eatery",
    "kitchen",
    "diner",
    "barbeque",
    "haldiram",
    "blinkit",
    "instamart",
  ],
  transport: [
    "uber",
    "ola",
    "rapido",
    "cab",
    "taxi",
    "metro",
    "bus",
    "petrol",
    "fuel",
    "parking",
    "train",
    "railway",
    "irctc",
    "flight",
    "airways",
    "indigo",
    "spicejet",
    "auto",
    "rickshaw",
    "fasttag",
    "toll",
  ],
  shopping: [
    "amazon",
    "flipkart",
    "myntra",
    "ajio",
    "shop",
    "store",
    "mall",
    "purchase",
    "order",
    "nykaa",
    "meesho",
    "bigbasket",
    "grofer",
    "reliance",
    "dmart",
    "zepto",
    "fashion",
    "cloth",
  ],
  entertainment: [
    "netflix",
    "prime",
    "hotstar",
    "spotify",
    "youtube",
    "movie",
    "cinema",
    "pvr",
    "inox",
    "game",
    "disney",
    "gaming",
    "bookmyshow",
    "ticket",
    "concert",
    "show",
    "zee5",
    "sonyliv",
  ],
  utilities: [
    "electricity",
    "water",
    "gas",
    "bill",
    "recharge",
    "airtel",
    "jio",
    "vi ",
    "bsnl",
    "wifi",
    "broadband",
    "prepaid",
    "postpaid",
    "bescom",
    "tpddl",
    "msedcl",
    "utility",
    "tata sky",
    "dish tv",
  ],
  health: [
    "medical",
    "pharmacy",
    "doctor",
    "hospital",
    "medicine",
    "clinic",
    "apollo",
    "health",
    "prescription",
    "1mg",
    "netmeds",
    "pharmeasy",
    "diagnostic",
    "lab",
    "pathlab",
    "ayurveda",
  ],
  education: [
    "course",
    "school",
    "college",
    "university",
    "book",
    "tuition",
    "fee",
    "udemy",
    "coursera",
    "skillshare",
    "byju",
    "vedantu",
    "unacademy",
    "duolingo",
    "study",
    "exam",
    "coaching",
  ],
  travel: [
    "hotel",
    "booking",
    "makemytrip",
    "oyo",
    "goibibo",
    "airbnb",
    "resort",
    "travel",
    "tour",
    "trip",
    "holiday",
    "vacation",
    "hostel",
    "yatra",
    "cleartrip",
  ],
};

export function categorizeExpense(text: string): Category {
  const lower = text.toLowerCase();
  for (const [category, words] of Object.entries(KEYWORDS) as [
    Exclude<Category, "other">,
    string[],
  ][]) {
    for (const word of words) {
      if (lower.includes(word)) return category;
    }
  }
  return "other";
}
